# Assignment 1
### Problem 1

In [1]:
import numpy as np

In [5]:
arr = np.random.randint(1,51,size=(5,4))


In [9]:
print(arr)

[[22 33 44 26]
 [30 49 21 13]
 [43 11  4 47]
 [18  9 17  7]
 [15  1 29 26]]


In [16]:
anti_diag = np.fliplr(arr).diagonal()
print(anti_diag)

[26 21 11 18]


In [22]:
max_val = np.max(arr, axis=1)
print(max_val)

[44 49 47 18 29]


In [24]:
mean_val = np.mean(arr)
print(mean_val)

23.25


In [30]:
new_arr = arr[arr > mean_val]
print(new_arr)


[33 44 26 30 49 43 47 29 26]


In [63]:
arr[-1,::-1]

array([26, 29,  1, 15], dtype=int32)

In [62]:
arr[::-1,0]

array([15, 18, 43, 30, 22], dtype=int32)

In [70]:
right = len(arr[0]) - 1
right

3

In [74]:
def numpy_boundary_traversal(arr):
  top = 0
  right = len(arr[0]) - 1
  bottom = len(arr) - 1
  left = 0
  out = []
  
  for i in range(left,right +1):
    out.append(arr[top][i])
  for i in range(top + 1, bottom + 1):
    out.append(arr[i][right])
  for i in range(right - 1,left - 1,-1):
    out.append(arr[bottom][i])
  for i in range(bottom - 1, top , -1):
    out.append(arr[i][left])
  return np.array(out)

print(numpy_boundary_traversal(arr))
  
    


[22 33 44 26 13 47  7 26 29  1 15 18 43 30]


# Problem 2

In [96]:
arr1 = np.random.uniform(0,10,size = 20)
arr1

array([4.83443785, 2.77762728, 8.0617698 , 5.67781213, 6.51040533,
       7.45711694, 3.99301605, 9.063425  , 2.85849556, 4.5930035 ,
       1.07448632, 1.52070054, 2.06655224, 6.04661261, 6.17804179,
       3.06482579, 8.43663608, 5.06256141, 2.22959072, 1.36280556])

In [97]:
arr1 = np.round(arr1, 2)
print(arr1)

[4.83 2.78 8.06 5.68 6.51 7.46 3.99 9.06 2.86 4.59 1.07 1.52 2.07 6.05
 6.18 3.06 8.44 5.06 2.23 1.36]


In [98]:
print(f'Maximum of the array:{np.max(arr1)}')
print(f'Minimum of the array:{np.min(arr1)}')
print(f'Median of the array:{np.median(arr1)}')

Maximum of the array:9.06
Minimum of the array:1.07
Median of the array:4.71


In [99]:
arr1 = np.array([x if x >5 else np.pow(x,2) for x in arr1])
arr1

array([23.3289,  7.7284,  8.06  ,  5.68  ,  6.51  ,  7.46  , 15.9201,
        9.06  ,  8.1796, 21.0681,  1.1449,  2.3104,  4.2849,  6.05  ,
        6.18  ,  9.3636,  8.44  ,  5.06  ,  4.9729,  1.8496])

In [108]:
def numpy_alternate_sort(arr):
  start = 0
  end = len(arr2) - 1
  out1 = []
  while start <= end:
    out1.append(arr2[start])
    out1.append(arr2[end])
    start += 1
    end -=1
  return np.array(out1)


print(numpy_alternate_sort(arr1))


[ 1.1449 23.3289  1.8496 21.0681  2.3104 15.9201  4.2849  9.3636  4.9729
  9.06    5.06    8.44    5.68    8.1796  6.05    8.06    6.18    7.7284
  6.51    7.46  ]


# Problem 3

In [109]:
import pandas as pd

In [123]:
student_names = ['Aryan', 'Isha', 'Rubel', 'Diya', 'Ritwik', 'Ananya', 'Rohan', 'Vipul', 'Arjun', 'Sneha']
subjects = ['Math', 'Science', 'English', 'History','English','Math','English','Science','Science','History']

scores = np.random.randint(50, 101, size=10)

# Create DataFrame
df = pd.DataFrame({
    'Name': student_names,
    'Subject': subjects,
    'Score': scores,
    'Grade': [''] * 10  # Initially empty
})

print(df)



     Name  Subject  Score Grade
0   Aryan     Math     76      
1    Isha  Science     52      
2   Rubel  English     65      
3    Diya  History     85      
4  Ritwik  English     85      
5  Ananya     Math     73      
6   Rohan  English     57      
7   Vipul  Science     69      
8   Arjun  Science     77      
9   Sneha  History     90      


In [124]:
df['Grade'] = df['Score'].apply(lambda x:'A' if x>=90 else 'B' if x >= 80 else 'C' if x >= 70 else 'D' if x >= 60 else 'F')
df

Name  Subject  Score Grade
0   Aryan     Math     76     C
1    Isha  Science     52     F
2   Rubel  English     65     D
3    Diya  History     85     B
4  Ritwik  English     85     B
5  Ananya     Math     73     C
6   Rohan  English     57     F
7   Vipul  Science     69     D
8   Arjun  Science     77     C
9   Sneha  History     90     A

In [125]:
df = df.sort_values(by= 'Score' , ascending=False)
df

Name  Subject  Score Grade
9   Sneha  History     90     A
3    Diya  History     85     B
4  Ritwik  English     85     B
8   Arjun  Science     77     C
0   Aryan     Math     76     C
5  Ananya     Math     73     C
7   Vipul  Science     69     D
2   Rubel  English     65     D
6   Rohan  English     57     F
1    Isha  Science     52     F

In [133]:
avg_score = df.groupby('Subject')['Score'].mean().reset_index()
avg_score.columns = ['Subject', 'Average Score']
print(avg_score)


   Subject  Average Score
0  English           69.0
1  History           87.5
2     Math           74.5
3  Science           66.0


In [146]:
def pandas_filter_pass(dataframe):
    return dataframe[dataframe['Grade'].isin(['A', 'B'])]



y = pandas_filter_pass(df)
type(y)

pandas.core.frame.DataFrame